class AppLocalization {
  static final Map<String, Map<String, String>> translations = {
        'en_US': {
          'login': 'Login',
          'create_account': 'Create Account',
          'home': 'Home',
          'register_complaint': 'Register Complaint',
          'feedback': 'Feedback',
          'profile': 'Profile',
          'settings': 'Settings',
          'logout': 'Logout',
          'edit_profile': 'Edit Profile',
          'change_password': 'Change Password',
          'notifications': 'Notifications',
          'language': 'Language',
          'theme': 'Theme',
          'dark_mode': 'Dark Mode',
          'light_mode': 'Light Mode',
          'aadhar_number': 'Aadhar Number',
          'password': 'Password',
          'submit': 'Submit',
          'cancel': 'Cancel',
          'save': 'Save',
          'delete': 'Delete',
          'edit': 'Edit',
          'loading': 'Loading...',
          'error': 'Error',
          'success': 'Success',
          'warning': 'Warning',
          'confirm': 'Confirm',
          'yes': 'Yes',
          'no': 'No',
          'close': 'Close',
          'back': 'Back',
          'next': 'Next',
          'previous': 'Previous',
          'welcome': 'Welcome',
          'welcome_back': 'Welcome Back',
          'enter_aadhar': 'Enter your Aadhar Number',
          'enter_password': 'Enter your password',
          'forgot_password': 'Forgot Password?',
          'dont_have_account': "Don't have an account?",
          'already_have_account': 'Already have an account?',
          'sign_up': 'Sign Up',
          'sign_in': 'Sign In',
          'overall_rating': 'Overall Rating',
          'submit_feedback': 'Submit Feedback',
          'feedback_history': 'Feedback History',
          'no_feedback': 'No feedback history',
          'complaint_title': 'Complaint Title',
          'complaint_description': 'Description',
          'location': 'Location',
          'category': 'Category',
          'status': 'Status',
          'date': 'Date',
          'time': 'Time',
          'submitted_on': 'Submitted on',
          'resolved_on': 'Resolved on',
          'resolution_date': 'Resolution Date',
          'contact_us': 'Contact Us',
          'about_us': 'About Us',
          'privacy_policy': 'Privacy Policy',
          'terms_conditions': 'Terms & Conditions',
          'app_version': 'App Version',
          'user_profile': 'User Profile',
          'my_complaints': 'My Complaints',
          'saved_items': 'Saved Items',
          'achievements': 'Achievements',
          'stats': 'Statistics',
          'total_complaints': 'Total Complaints',
          'resolved_issues': 'Resolved Issues',
          'impact_score': 'Impact Score',
          'avg_resolution_time': 'Avg Resolution Time',
          'upload_photo': 'Upload Photo',
          'change_picture': 'Change Picture',
          'picture_updated': 'Picture updated successfully',
          'profile_updated': 'Profile updated successfully',
          'are_you_sure': 'Are you sure?',
          'confirm_logout': 'Are you sure you want to logout?',
          'full_name': 'Full Name',
          'email': 'Email',
          'phone': 'Phone',
          'address': 'Address / Location',
          'government_id': 'Government ID',
          'id_type': 'ID Type',
          'id_number': 'ID Number',
          'english': 'English',
          'hindi': 'हिंदी',
        },
        'hi_IN': {
          'login': 'लॉगिन करें',
          'create_account': 'खाता बनाएं',
          'home': 'होम',
          'register_complaint': 'शिकायत दर्ज करें',
          'feedback': 'प्रतिक्रिया',
          'profile': 'प्रोफाइल',
          'settings': 'सेटिंग्स',
          'logout': 'लॉगआउट',
          'edit_profile': 'प्रोफाइल संपादित करें',
          'change_password': 'पासवर्ड बदलें',
          'notifications': 'सूचनाएं',
          'language': 'भाषा',
          'theme': 'थीम',
          'dark_mode': 'डार्क मोड',
          'light_mode': 'लाइट मोड',
          'aadhar_number': 'आधार संख्या',
          'password': 'पासवर्ड',
          'submit': 'जमा करें',
          'cancel': 'रद्द करें',
          'save': 'सहेजें',
          'delete': 'हटाएं',
          'edit': 'संपादित करें',
          'loading': 'लोड हो रहा है...',
          'error': 'त्रुटि',
          'success': 'सफल',
          'warning': 'चेतावनी',
          'confirm': 'पुष्टि करें',
          'yes': 'हाँ',
          'no': 'नहीं',
          'close': 'बंद करें',
          'back': 'वापस',
          'next': 'अगला',
          'previous': 'पिछला',
          'welcome': 'स्वागत है',
          'welcome_back': 'स्वागत है',
          'enter_aadhar': 'अपना आधार नंबर दर्ज करें',
          'enter_password': 'अपना पासवर्ड दर्ज करें',
          'forgot_password': 'पासवर्ड भूल गए?',
          'dont_have_account': 'खाता नहीं है?',
          'already_have_account': 'पहले से खाता है?',
          'sign_up': 'साइन अप करें',
          'sign_in': 'साइन इन करें',
          'overall_rating': 'समग्र रेटिंग',
          'submit_feedback': 'प्रतिक्रिया जमा करें',
          'feedback_history': 'प्रतिक्रिया इतिहास',
          'no_feedback': 'कोई प्रतिक्रिया इतिहास नहीं',
          'complaint_title': 'शिकायत का शीर्षक',
          'complaint_description': 'विवरण',
          'location': 'स्थान',
          'category': 'श्रेणी',
          'status': 'स्थिति',
          'date': 'तारीख',
          'time': 'समय',
          'submitted_on': 'को जमा किया गया',
          'resolved_on': 'को हल किया गया',
          'resolution_date': 'समाधान तारीख',
          'contact_us': 'हमसे संपर्क करें',
          'about_us': 'हमारे बारे में',
          'privacy_policy': 'गोपनीयता नीति',
          'terms_conditions': 'शर्तें और शर्तें',
          'app_version': 'ऐप संस्करण',
          'user_profile': 'उपयोगकर्ता प्रोफाइल',
          'my_complaints': 'मेरी शिकायतें',
          'saved_items': 'सहेजे गए आइटम',
          'achievements': 'उपलब्धियां',
          'stats': 'आंकड़े',
          'total_complaints': 'कुल शिकायतें',
          'resolved_issues': 'हल किए गए मुद्दे',
          'impact_score': 'प्रभाव स्कोर',
          'avg_resolution_time': 'औसत समाधान समय',
          'upload_photo': 'फ़ोटो अपलोड करें',
          'change_picture': 'तस्वीर बदलें',
          'picture_updated': 'तस्वीर सफलतापूर्वक अपडेट की गई',
          'profile_updated': 'प्रोफाइल सफलतापूर्वक अपडेट किया गया',
          'are_you_sure': 'क्या आप निश्चित हैं?',
          'confirm_logout': 'क्या आप निश्चित रूप से लॉगआउट करना चाहते हैं?',
          'full_name': 'पूरा नाम',
          'email': 'ईमेल',
          'phone': 'फोन',
          'address': 'पता / स्थान',
          'government_id': 'सरकारी आईडी',
          'id_type': 'आईडी प्रकार',
          'id_number': 'आईडी नंबर',
          'english': 'English',
          'hindi': 'हिंदी',
        }
      };

  static String translate(String key, String locale) {
    return translations[locale]?[key] ?? translations['en_US']?[key] ?? key;
  }

  static Map<String, String> getCurrentLanguageMap(String locale) {
    return translations[locale] ?? translations['en_US'] ?? {};
  }
}
